# Generated by Django 4.1.13 on 2024-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(choices=[('puppy', 'Puppy/Kitten'), ('adult', 'Adult'), ('senior', 'Senior')], upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('goose', 'Goose')], max_length=100),
        ),
    ]
